### ISSUE TITLE
[Feature request] Data streaming

### ISSUE THREAD

**Issue by acheong08** [FlorianREGAZ/Python-Tls-Client#32]
Similar to Python requests: https://stackoverflow.com/questions/60343944/how-does-requests-stream-true-option-streams-data-one-block-at-a-time

**Comment by GunGunGun** [comment]
Streaming would be great to have because it allows user to make decision about skipping body data or buffer fetching to print result to client, which is great in many situations:

- Content is too big, like 2GB and memory limitation like 2GB RAM, then if you fetch everything into memory you'll get OOM error
- In proxy environment, you may want to abort the body data if the response header doesn't match some of your criterias
I'll try to look into the code and implement this feature, shouldn't be that hard considering we're fetching data from Go TLS Client which probably allow data streaming.

**Comment by GunGunGun** [comment]
Actually after researching the API of tls-client by bogdanfinn, I can't find any information about stream being made available, so it looks like to have this stream feature we first need to do something with the core first, which is the Go Client https://github.com/bogdanfinn/tls-client-api

**Comment by FlorianREGAZ** [comment]
Hey, I don't think it'll be possible to add this soon sadly. :/
